[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mds"
version = "0.0.1"
description = "Package for running the data pipeline for Modern Data Stack with Azure and Databricks"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Godwin AMEGAH", email = "komlan.godwin.amegah@gmail.com"}
]
dependencies = [
    "pyyaml",
    "pandas",
    "XlsxWriter",
    "requests",
    "unidecode",
    "jsonref",
    "mergedeep",
    "Jinja2"
]

[project.scripts]
mds = "mds:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["mds"]
exclude = ["*tests*", "*tests"]

[tool.setuptools.package-data]
mds = ["py.typed"]
